### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by iwarner** [ipeirotis/wikiSyno#26]
Hiya

Can you let me know when the API was last updated with the correct data from Wikipedia please?

Noticed the project source has not been updated for a while and copyright on site is still 2012 - If you also want to transfer the project to me I have a project now that requires something similar and could use this

Many thanks

Ian

**Comment by ipeirotis** [comment]
I do not think we updated it after 2012 and I am afraid that I do not plan on setting a systematic process for updates. You should feel free though to deploy the service on your own. Code and data is freely available :)
